POST http://localhost:3000/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkwMTE3Njg1fQ.hLRhfbhO3pWOdPjw60cjT5Zvavr7HZxZx8B_3l85lUk

{
"name": "books"
}

###
GET http://localhost:3000/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkwMTE3Njg1fQ.hLRhfbhO3pWOdPjw60cjT5Zvavr7HZxZx8B_3l85lUk

###
GET http://localhost:3000/category/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkwMTE3Njg1fQ.hLRhfbhO3pWOdPjw60cjT5Zvavr7HZxZx8B_3l85lUk

###
PATCH http://localhost:3000/category/11
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkwMTE3Njg1fQ.hLRhfbhO3pWOdPjw60cjT5Zvavr7HZxZx8B_3l85lUk

{
  "name": "games"
}

###
DELETE http://localhost:3000/category/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkwMTE3Njg1fQ.hLRhfbhO3pWOdPjw60cjT5Zvavr7HZxZx8B_3l85lUk